project:
  type: book
  output-dir: site

book:
  title: "APRENDIZADO DE MÁQUINA COM PYTHON"
  reader-mode: true
  back-to-top-navigation: true
  search: true
  repo-actions: [issue]
  sharing: [twitter,facebook,linkedin]
  favicon: uff-brasao.jpg
  page-footer:
    left: |
      Orientação: Douglas Rodrigues (UFF) e Karina Yaginuma (UFF). <br>
      Equipe atual: Gabriel Caetano, Guilherme Ceacero, Claudionor Ferreira e Fenício Porto.
  repo-url: https://github.com/CienciaDeDadosUFF/python.github.io
  downloads: [pdf]
  #repo-actions: false #apenas se versão do quarto > 1.4 
  
  
  chapters:
    - index.qmd
    - "caderno1.qmd"
    - "caderno2.qmd"
    - "ConceitosGeraisDeEstatistica.qmd"
    - "VisualizacaoDeDados.qmd"
    - "EstimativaPorIntervalos.qmd"
    - "TesteDeHipotesesParte1.qmd"
    - "TesteDeHipotesesParte2.qmd"



#bibliography: references.bib

format:
  html:
    theme:
      dark: darkly
      light: flatly
  pdf:
    documentclass: scrreprt

editor: visual
